name: Integration Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Configure Git to use PAT
        shell: sh
        run: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - name: Self test
        id: selftest
        # Put your action repo here
        uses: kousikmitra/cover-agent-ci@main
        env:
          githubToken: ${{ secrets.GH_TOKEN }}
        with:
          sourceDir: ${{ github.workspace }}
          githubToken: ${{ secrets.GH_TOKEN }}
          apiEndpoint: "https://dev-prod-codereview.openai.azure.com/openai/deployments/gpt-latest"
          modelName: "gpt-4-turbo"
          maxIterations: 5
          desiredCoverage: 60
      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.changes }}"
